version: '3.9'

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=10031992
    
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.1
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.8.1
    volumes:
      - ./config/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
      - ./logs/gallery-service.log:/gallery-service.log
    depends_on:
      - elasticsearch
  
  # gallery_service:
  #   container_name: gallery-service
  #   build:
  #     context: ./gallery-service
  #   ports:
  #     - "8081:8082"
  #   volumes:
  #     - ./logs/gallery-service.log:/logs/gallery-service.log
