version: '3.9'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.1.3
    volumes:
      - ./config/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
  
  gallery_service:
    container_name: gallery_service
    build:
      context: ./gallery-service
    ports:
      - "8081:8082"